"""Stage 6 — Migration Report. Aggregate flags + stats into json + html.

The report is a first-class deliverable: it tells a human exactly what remains.
See docs/specs/modules/pipeline.md.
"""

from __future__ import annotations

import html
import json
from pathlib import Path

from engines.t2pbi.ir import Severity, Workbook


def compute_stats(wb: Workbook) -> dict[str, int]:
    tables = wb.all_tables()
    cols = [c for t in tables for c in t.columns]
    calc = [c for c in cols if c.is_calculated]
    return {
        "datasources": len(wb.datasources),
        "tables": len(tables),
        "columns": len(cols),
        "calculated_fields": len(calc),
        "calculated_translated": len([c for c in calc if c.dax]),
        "parameters": len(wb.parameters),
        "relationships": len(wb.relationships),
        "worksheets": len(wb.worksheets),
        # Each filter is reported individually, so each one has to be counted
        # individually too - a flag about an object outside the total makes the
        # total a fiction.
        "filters": sum(len(ws.filters) for ws in wb.worksheets),
        # Same rule for every field placed on a visual. `P2.2` started
        # reading the colour, size, text and tooltip shelves, and each
        # placement that is not bound is now reported - so each one has to
        # be inside the total, or reporting them makes the arithmetic worse
        # than the silence did.
        "bindings": sum(len(ws.bindings) for ws in wb.worksheets),
        "dashboards": len(wb.dashboards),
        "flags": len(wb.flags),
        "manual_flags": len([f for f in wb.flags if f.severity == Severity.MANUAL]),
    }


def write_report(wb: Workbook, out_dir: str | Path) -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    stats = compute_stats(wb)

    data = {
        "stats": stats,
        "flags": [
            {
                "item": f.item,
                "severity": f.severity.value,
                "reason": f.reason,
                "stage": f.stage,
            }
            for f in wb.flags
        ],
    }
    (out / "migration-report.json").write_text(
        json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n"
    )

    (out / "migration-report.html").write_text(
        _render_html(stats, wb), encoding="utf-8", newline="\n"
    )
    return out / "migration-report.html"


def _render_html(stats: dict[str, int], wb: Workbook) -> str:
    rows = "".join(
        f"<tr><td>{html.escape(k.replace('_', ' '))}</td><td>{v}</td></tr>"
        for k, v in stats.items()
    )

    def flag_rows(sev: Severity) -> str:
        items = [f for f in wb.flags if f.severity == sev]
        if not items:
            return "<p>None.</p>"
        body = "".join(
            f"<tr><td>{html.escape(f.item)}</td><td>{html.escape(f.stage)}</td>"
            f"<td>{html.escape(f.reason)}</td></tr>"
            for f in items
        )
        return (
            "<table><thead><tr><th>Item</th><th>Stage</th><th>Reason</th></tr>"
            f"</thead><tbody>{body}</tbody></table>"
        )

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>t2pbi Migration Report</title>
<style>
body{{font-family:Segoe UI,Arial,sans-serif;margin:2rem;color:#222}}
h1{{margin-bottom:.2rem}} table{{border-collapse:collapse;margin:.5rem 0 1.5rem}}
td,th{{border:1px solid #ccc;padding:.35rem .6rem;text-align:left}}
.manual{{color:#b00020}}
</style></head><body>
<h1>Tableau &rarr; Power BI Migration Report</h1>
<p>Generated by t2pbi. Source Tableau version: {html.escape(wb.version or 'unknown')}.</p>
<h2>Summary</h2>
<table><tbody>{rows}</tbody></table>
<h2 class="manual">Needs manual work (MANUAL)</h2>
{flag_rows(Severity.MANUAL)}
<h2>Warnings</h2>
{flag_rows(Severity.WARNING)}
<h2>Info</h2>
{flag_rows(Severity.INFO)}
</body></html>
"""
